apiVersion: v1
kind: Pod
metadata:
  name: healthy-pod
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx
      args:
      - /bin/sh
      - -c
      - touch /tmp/healthy
      livenessProbe:
        initialDelaySeconds: 5
        periodSeconds: 3
        timeoutSeconds: 1
        failureThreshold: 5
        exec:
          command:
          - cat 
          - /tmp/healthy
      readinessProbe:
        initialDelaySeconds: 5
        periodSeconds: 3
        timeoutSeconds: 1
        failureThreshold: 7
        exec:
          command:
          - cat 
          - /tmp/healthy
     
      